### ISSUE TITLE
Build scripts don't completely work

### ISSUE THREAD

**Issue by puddly** [Dafang-Hacks/Main#22]
The `live` submodule references the toolchain directory's [old name](https://github.com/Dafang-Hacks/live/blob/227e4c8b24fca0cf19936864d4006effe8995d40/config.dafang#L26), which causes `compile-libraries.sh` to fail unless `toolchain` is symlinked to the old name.

I've also [combined all of the `compile.sh`](https://github.com/puddly/Main/blob/build-script-fixes/compile-libraries.sh) scripts contained in the submodules, since they are all really three lines long once you get rid of the common environment variables.

Any thoughts? I'd like to lock down `freetype2` to a stable version instead of keeping it as a Git submodule tracking potentially breaking changes, but that'd require pulling it into the current source tree or keeping it external and just cloning the latest stable tag from within the build script.

**Comment by nik0** [comment]
I guess you can reference a submodule particular commit. I did a quick google search on "Fix the submodule to a particular commit"
Is it what you are looking for ? Now I don't know if it is a good idea. It should be interesting to get the last bug fix.

**Comment by schemacs** [comment]
@puddly Thanks for pointing this out, I just do `ln -s /root/Main/toolchain /root/Main/mips-gcc472-glibc216-64bit` when building with docker.
