### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dpeddi** [Dafang-Hacks/Main#31]
(1) strip library/binary
(2) move to buildroot like openfang
(3) move to musl instead of libc (like openwrt).  (depend 2)

by doing so the rootfs could fit on 25q64 flash

**Comment by EliasKotlyar** [comment]
1) Maybe possible : However i suppose that it will be still really big.
2) sure, that should be possible
3) we are using ulibc already. i am not sure if it would improve the situation.

I have considered shrinking down the binaries, but its not worth the effort. Its cheaper to buy a microsd that will hold all the data which is needed.

**Comment by dpeddi** [comment]
According to this table:
http://www.etalabs.net/compare_libcs.html
But it seems to be fast like ulibc and produces smallest binary then ulibc, but often programs need patches to be able to compile against must, but on openwrt source there are tons of example.

I haven't found time yet to test your work on my unitoptek m201f (sannce i21ag clones) but a day I hope it will fit on internal flash.

**Comment by lcfaria** [comment]
in the file 
mqtt-status-interval.sh 
line 31 and 32 is duplicated
