### ISSUE TITLE
v4l2rtspserver-master won't work without its ini file

### ISSUE THREAD

**Issue by danergo** [Dafang-Hacks/Main#32]
Hi,

I'm using a Dafang camera for this hack.
If I copy the prebuilt stuff onto the SD card v4l2rtspserver-master is working fine.

However if I compile my own version with this repo:
1.) v4l2rtspserver-master.ini config file HAS to be in /system/sdcard/bin
2.) v4l2rtspserver-master will listen only on rtsp://IP:1/ (port=1 does not matter what I write after -P on command line)
3.) /tmp/v4l2rtspserver-master.log contains very small amount of log compared to the prebuilt one.

Could someone please update this repo to the one can create the prebuilt v4l2rtspserver-master?
Thanks!

**Comment by danergo** [comment]
Is there still anyone here? Would be nice if we could have a fresh version in the git and not something outdated sh*t.

**Comment by danergo** [comment]
Also would be nice if someone at least post a reply to ANY of my issues.

**Comment by danergo** [comment]
Anyone?

**Comment by ThatUsernameAlreadyExist** [comment]
To get working version of v4l2rtspserver-master (in current hacks enviroment)  you need to revert folder 'v4l2rtspserver-master' to revision [3ec04dc907a89237118ca4a64d73f060fcb6055c](https://github.com/Dafang-Hacks/Main/commit/3ec04dc907a89237118ca4a64d73f060fcb6055c#diff-5817e09e38ddc5b799c5a60c89a7f1d9)

**Comment by danergo** [comment]
Getimage scripts is not able to get any picture from the sensor even with that reverted version.

How getimage supposed to be working?
