### ISSUE TITLE
is it possible to compile ffmpeg for the camera ?

### ISSUE THREAD

**Issue by xforze** [Dafang-Hacks/Main#33]
Would it be possible to compile ffmpeg to stream the video data to a remote proxy like ffserver ?
It should be something like this:
`ffmpeg -f v4l2 -i /dev/video0 http://remoteIP:8080/feed.ffm`

Or is it already possible with the "onboard" tools ?
It would be great to have the functionality that the camera starts automatically streaming to a remote server on which is ffserver listening.

**Comment by EliasKotlyar** [comment]
I suppose that you can compile it, but you wouild not able to run it, because it  requires more cpu-power. However you can still try to compile it
