### ISSUE TITLE
OSD is not visible

### ISSUE THREAD

**Issue by levurusov** [Dafang-Hacks/Main#38]
Hi,
I try to use OSD on T10-based device with H62 sensor. Using current state of this repo OSD seems broken because now there is no way to set `m_osdOn` to true. I fixed it and now `timestamp_osd.setPixel` tries to set pixels with valid coordinates lying inside of bounds. But there is no OSD on the image. v4l2trspserver-master works fine, there is no error and debug messages. I used different colors and even tried to force `timestamp_osd.setPixel` not to use transparent "color" at all but nothing changed, also built version before the "ConfigReader" series of commits with the same result. Can you advice to check anything else?

**Comment by nik0** [comment]
Did you try the example that is comming with imp?
You can also check this: https://github.com/geekman/t20-rtspd/commit/f30f0e86849a05a8d3f00608471348a8dd36e481
