### ISSUE TITLE
Change number of video buffers to two

### ISSUE THREAD

**Issue by Yannik** [Dafang-Hacks/Main#48]
In [this](https://github.com/geekman/t20-rtspd/commit/f30f0e86849a05a8d3f00608471348a8dd36e481) patch, geekman lowers the number of video buffers per channel to two. Supposedly, the `iCamera` stock binary is doing the same. According to geekman, this reduces the memory usage and therefore enables 1080p even on 64MB cameras.

Has anyone (@nik0) tried this? Other thoughts on the topic?

**Comment by nik0** [comment]
I implemented (not the  nVBs stuff)
Check the .ini file https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/v4l2rtspserver-master.ini
POOLSIZE parameter. I didn’t test it I don’t have this camera

**Comment by Yannik** [comment]
@nik0 
I know that you added the POOLSIZE parameter.

I've opened this issue about the number of video buffers (`nrVBs`).

**Comment by nik0** [comment]
Ok 
Need to change that 😜
