### ISSUE TITLE
How does getimage work?

### ISSUE THREAD

**Issue by tachang** [Dafang-Hacks/Main#64]
I am having a really hard time trying to figure out how getimage works.
It kinda looks like you've patched the v4l2 code so it puts the image into the shared memory region.

And then getimage just reads it.

However the key you use is "/usr/include","x" while the getimage is just "/usr/","1" which I find odd.

Is this correct or am I missing something?

**Comment by nik0** [comment]
/usr/include is used when the whole stream is outputed in memory (When the output file is set to "memory", not sure this option still exists).
Anyway the image is set to shared memory in line 379 of file ImpEncoder.cpp

**Comment by tachang** [comment]
Thanks managed to figure it out. I am attempting to build a new project based on this and openfang to try and move things forward. Cheers.
