### ISSUE TITLE
Updated toolchains

### ISSUE THREAD

**Issue by tssva** [Dafang-Hacks/Main#7]
I have gathered a couple of toolchains from Ingenic which are newer than the one in the repo. I have mips-gcc472-glibc216-64bit-r2.4.0 and mips-gcc520-glibc222-64bit-r3.2.1. If you are interested in trying them they can be found at http://github.com/tssva/ingenic-toolchains.

**Comment by EliasKotlyar** [comment]
Many thanks! I will try it out. If you have any other information&code, please share it.
