### ISSUE TITLE
why is openssl built statically?

### ISSUE THREAD

**Issue by claud9999** [Dafang-Hacks/Main#76]
The build process for openssl creates a static binary, which uses more space in the filesystem and more space in memory if multiple programs use the same shared library. How about we use the dynamic library? Also, by default, we should strip binaries/libraries of their symbol tables to save additional resources.

**Comment by claud9999** [comment]
Also there are a number of build script issues throughout the Modules subdirectory. I plan to go through them all and clean them up and simplify so that they all build as expected on Ubuntu 20.04 (if there's a different distro that is expected for folks to build in, I'm flexible.)

**Comment by nik0** [comment]
No problem for all of that @claud9999 
As I already said I don't have time left for this project at this moment ...
Ubunutu seems fine for me (I used a docker on Windows anyway ...)

**Comment by jmtatsch** [comment]
That would all be highly appreciated. Ubuntu 20.04 sounds great as default build platform.
